config/routes.rb
Rails.application.routes.draw do
  root   'pages#home'
  get    '/help',                 to: 'pages#help'
  resources :cities,          only: [:create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
require 'net/http'
require 'json'

class City < ApplicationRecord
  before_save   :downcase_name 
  before_create :add_timezone
  validates :name, presence: true, uniqueness: { case_sensitive: false }, 
                   length: { maximum: 50 }

  class << self
    # Retrieves the weather json
    def get_weather(name, type="weather")
      api_key = Rails.application.credentials.open_weather_map[:api_key]

      # TODO: Change units based on locale
      uri = URI("http://api.openweathermap.org/data/2.5/#{type}?q=#{URI.encode(name)}&units=imperial&appid=#{api_key}")
    
      # Download and parse the JSON from the api
      res = JSON.parse(Net::HTTP.get(uri))
    end
  end

  private

  # Converts city name to all lower-case.
  def downcase_name
    name.downcase!
  end

  # Lookup the correct timezone based on the latitude and longitude.
  def add_timezone
    res = City.get_weather(name)

    begin
      self.timezone = Timezone.lookup(res['coord']['lat'], res['coord']['lon']).name
    rescue Timezone::Error::Base => e
      puts "Timezone Error: #{e.message}"
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :set_locale
    
  def set_locale
    I18n.locale = params[:locale] || I18n.default_locale
  end

end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController

  def create
    @city = City.new(city_params)

    respond_to do |format|
      if @result = @city.save
        format.html { redirect_to root_url }
        format.js
      else
        format.html {
          @city.errors.full_messages.each do |msg|
            flash[:danger] = msg
          end
          redirect_to root_url
        }
        format.js
      end
    end
  end

  def destroy
    @city = City.find(params[:id])

    respond_to do |format|
      if @result = @city.destroy()
        format.html { redirect_to root_url }
        format.js
      else
        format.html {
          @city.errors.full_messages.each do |msg|
            flash[:danger] = msg
          end
          redirect_to root_url
        }
        format.js
      end
    end
  end

  private

    def city_params
      params.require(:city).permit(:name)
    end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @city = City.new
    @cities = City.all
  end

  def help
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  # Returns the full title on a per-page basis.
  def full_title(page_title = '')
    base_title = t('app.name')
    if page_title.empty?
      base_title
    else
      page_title + " | " + base_title
    end
  end

  # Returns 'active' if the current path is the active class, otherwise empty
  def active?(test_path)
    return 'active' if current_page? test_path
  end

end

app/helpers/cities_helper.rb
module CitiesHelper
  # Retrieves the current temperature from the api
  def temperature(name)
    res = City.get_weather(name)
    res['main']['temp'].to_i
  end

  # Retrieves the forecast temperature from the api
  def forecast(name)
    res = City.get_weather(name, "forecast")

    unless res['list'].nil?
      temps = []
      res['list'][0, 3].each do |data|
        temps << data['main']['temp'].to_i
      end
      
      # TODO: Make a loop and add date time tooltips
      content_tag(:h4, temps[0]) + content_tag(:h5, temps[1]) + content_tag(:h6, temps[2])
    end
  end

  # Return the datetime in the appropriate timezone
  def dt(timezone, time="now")
    unless timezone.nil?
      tz = Timezone.fetch(timezone)
      if time == "now"
        return tz.utc_to_local(Time.now)
      end
      return tz.utc_to_local(Time.now)
    end
    return Time.now
  end

  # Returns a name that can be used as a css id
  def css_id(name)
    name.downcase.strip.gsub(' ', '-').gsub(/[^\w-]/, '')
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/cities/_city.html.erb
<div class="col-sm-3 weather-col" id="<%= css_id(city.name) %>-col">
  <div class="card text-center">
    <div class="card-body weather-card">
      <h4 class="card-title"><%= city.name.capitalize %></h4>
      <%= link_to '<span>&times;<span>'.html_safe, city, remote: true, method: :delete, class: 'close' %>
      <h6 class="card-subtitle text-muted"><%= l dt(city.timezone), format: :short %></h6>
      <div class="temperature">
        <h1><%= temperature(city.name) %><span class="degree"></span></h1>
        <div class="forecast" id="<%= css_id(city.name) %>-forecast"><%= raw forecast(city.name) %></div>
      </div>
    </div>
  </div>
</div>

app/views/cities/create.js.erb
<% if @result %>
  $('#add-city')[0].reset();
  $('#errors').empty();
  $('.scroll').append("<%= j render @city %>");
  console.log("Successfully added <%= @city.name.capitalize %>.")
<% else %>
  $('#add-city')[0].reset();
  $('#errors').html('<%= j render 'shared/error_messages', object: @city %>');
<% end %>

app/views/cities/destroy.js.erb
<% if @result %>
  $('#errors').empty();
  $('#<%= css_id(@city.name) %>-col').remove();
  console.log("Successfully removed <%= @city.name.capitalize %>.")
<% else %>
  $('#errors').html('<%= j render 'shared/error_messages', object: @city %>');
<% end %>

app/views/layouts/_debug.html.erb
<% if Rails.env.development? %>
  <div class="collapse container" id="debug">
    <%= debug(params) %>
  </div>
<% end %>

app/views/layouts/_debug_link.html.erb
<% if Rails.env.development? %>
  <li class="debug-link">
    <button class="btn btn-default btn-sm" type="button" data-toggle="collapse" data-target="#debug" aria-expanded="false" aria-controls="debug">
      <%= t('menu.debug') %>
    </button>
  </li>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="footer bg-white">
  <div class="container bg-white">
  <small><%= t('app.copyright') %></small>
  <nav>
    <ul>
      <li><%= link_to t('menu.about'), '#' %></li>
      <li><%= link_to t('menu.contact'), '#' %></li>
      <%= render 'layouts/debug_link' %>
    </ul>
  </nav>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header>
  <nav class="navbar navbar-expand-md fixed-top navbar-dark">
    <div class="container">
      <%= link_to t('app.name'), root_path, id: "logo", class: "navbar-brand" %>
      <%= render 'shared/add_city_form' %>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarCollapse">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item"><%= link_to t('menu.home'), root_path, class: "nav-link #{active?(root_path)}" %></li>
          <li class="nav-item"><%= link_to t('menu.help'), help_path, class: "nav-link #{active?(help_path)}" %></li>
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/_rails_default.html.erb
<%= csrf_meta_tags %>
<%= csp_meta_tag %>

<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= render 'layouts/rails_default' %>
    <%= render 'layouts/shim' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <div id="errors">
        <% flash.each do |message_type, message| %>
          <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
        <% end %>
      </div>
      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
    <%= render 'layouts/debug' %>
  </body>
</html>

app/views/pages/help.html.erb
<% provide(:title, "Help") %>
<h1 class="text-center"><%= t('menu.help') %></h1>
<p>
  This application displays the weather.
</p>

app/views/pages/home.html.erb
<div class="row scroll">
  <%= render @cities %>
</div>

app/views/shared/_add_city_form.html.erb
<%= form_with(model: @city, id: 'add-city') do |f| %>
  <div class="input-group align-middle" style="width: auto">
    <%= f.text_field :name, class: 'form-control', placeholder: t('menu.add.city_name') %>
    <div class="input-group-append">
      <%= f.submit t('menu.add.add_city'), data: { "disable-with": "Saving..." }, class: "btn btn-default" %>
    </div>
  </div>
<% end %>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <% object.errors.full_messages.each do |msg| %>
    <%= content_tag(:div, msg, class: "alert alert-danger") %>
  <% end %>
<% end %>